### ISSUE TITLE
Action can not find setup action in self-hosted runners

### ISSUE THREAD

**Issue by kuhnroyal** [dahlia/submark#7]
When trying to use `dahlia/submark` on a self-hosted runner, it fails to find the `dahlia/submark/setup` action:

```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/path/to/runner/_work/my-project/my-project/setup'. Did you forget to run actions/checkout before running your local action?
```
This happens on Linux and MacOS.
Something with the path seems off, I will try to get some debug logging.

Can I run `dahlia/submark/setup` manually beforehand, will the main action detect that it is already configured?

**Comment by kuhnroyal** [comment]
Runner debug log shows a different location:
```
Download action repository 'dahlia/submark@7d44d75a4dcfd351258491f26898e836b0521ce0' (SHA:7d44d75a4dcfd351258491f26898e836b0521ce0)
##[debug]Download 'https://api.github.com/repos/dahlia/submark/tarball/7d44d75a4dcfd351258491f26898e836b0521ce0' to '/path/to/runner/_work/_actions/_temp_41868f75-c368-4ff6-b927-d5b93b71a9f6/5311a86e-d87f-49bc-953b-4ac3d910f7f8.tar.gz'
##[debug]Unwrap 'dahlia-submark-7d44d75' to '/path/to/runner/_work/_actions/dahlia/submark/7d44d75a4dcfd351258491f26898e836b0521ce0'
##[debug]Archive '/path/to/runner/_work/_actions/_temp_41868f75-c368-4ff6-b927-d5b93b71a9f6/5311a86e-d87f-49bc-953b-4ac3d910f7f8.tar.gz' has been unzipped into '/path/to/runner/_work/_actions/dahlia/submark/7d44d75a4dcfd351258491f26898e836b0521ce0'.
##[debug]Action 'dahlia/submark@7d44d75a4dcfd351258491f26898e836b0521ce0' already downloaded at '/path/to/runner/_work/_actions/dahlia/submark/7d44d75a4dcfd351258491f26898e836b0521ce0'.
```

**Comment by kuhnroyal** [comment]
Maybe this will help: https://stackoverflow.com/a/66643346/2553215

Using `${{github.action_path}}/setup/` here: https://github.com/dahlia/submark/blob/main/action.yaml#L57

**Comment by kuhnroyal** [comment]
Sadly a dynamic `uses:` is not supported...

**Comment by dahlia** [comment]
@kuhnroyal Have you ever found any workaround?

**Comment by kuhnroyal** [comment]
Sadly not, so far

**Comment by kuhnroyal** [comment]
Probably something like extracting setup into a script and calling it from both actions.
I am wondering why it would work on Github hosted runners with this.

**Comment by kuhnroyal** [comment]
Ok, this doesn't work at all: see https://github.com/kuhnroyal/submark_test/runs/6672494094?check_suite_focus=true

**Comment by kuhnroyal** [comment]
This only works inside the submark repository.

**Comment by kuhnroyal** [comment]
After working around this by removing the setup part and manually running `dahlia/submark/setup` beforehand, I get another error.
Not sure if this is related to private runners.

```
Run kuhnroyal/submark@081418786c64195fd80ef7bf8253d47d7292ce69
Run from __future__ import print_function
Traceback (most recent call last):
  File "/path/to/runner/_work/_temp/aa8be0ca-d542-467b-8aab-8844d2a83698.py", line 87, in <module>
    exit_code = subprocess.call(args, stderr=stderr)
  File "/path/to/runner/_work/_tool/Python/3.10.4/x64/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/path/to/runner/_work/_tool/Python/3.10.4/x64/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/path/to/runner/_work/_tool/Python/3.10.4/x64/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''
Error: Process completed with exit code 1.
```

**Comment by dahlia** [comment]
Recently I also experienced the same issue… it might be fixed if I change the following line to `uses: dahlia/submark/setup` 🤔:

https://github.com/dahlia/submark/blob/ff45d9f552483bdf2f740a60168af6878eddad3c/action.yaml#L57

**Comment by dahlia** [comment]
@kuhnroyal <del timestamp="2022-07-11T11:50:00+09:00">Could you try with [`uses: dahlia/submark@bugfix/7`](https://github.com/dahlia/submark/tree/bugfix/7)?</del> <ins timestamp="2022-07-11T11:50:00+09:00">I removed *bugfix/7* branch and instead it's now merged to the _main_ branch.</ins>

**Comment by vscheuber** [comment]
@dahlia I have been experiencing that issue using github hosted runners. I changed my action to use:

[uses: dahlia/submark@bugfix/7](https://github.com/dahlia/submark/tree/bugfix/7)

And that solved the issue for me in github hosted runners. Would love to see this branch merged so I know my pipeline won't break going forward.

**Comment by dahlia** [comment]
@vscheuber Thanks for your feedback!  I just merged the fix.

However, I'm going to keep this issue open, because I haven't tested it with self-hosted runners.  Please anybody who tested it with self-hosted runners tell me if it actually works or not.

**Comment by vscheuber** [comment]
Fantastic! Thank you @dahlia . I have switched my pipeline to use @main and will let you know if I hit any further problems.

**Comment by kuhnroyal** [comment]
I currently do not have a pipeline with this on a self-hosted runner anymore.
From a security perspective I don't like the usage of the `main` branch there but also do not have a better idea.

**Comment by dahlia** [comment]
> From a security perspective I don't like the usage of the `main` branch there but also do not have a better idea.

I agree and am going to make a new tag if this fix is proved to work well on self-hosted runners.

**Comment by maelchiotti** [comment]
Hi @dahlia. I have this issue on GitHub hosted runners. It's fixed however if I use the main branch. I don't have a self-hosted runner to test this on, but maybe a new release should be published with the fix, while keeping the issue open? This way I wouldn't have to use the main branch.

**Comment by dahlia** [comment]
It's already fixed, but I forgot to close this issue. You can now use the _main_ branch.

**Comment by maelchiotti** [comment]
Yes I do use the main branch, but shouldn't this be included in a release then?
